# TensorFlow script mode training and serving

Script mode is a training script format for TensorFlow that lets you execute any TensorFlow training script in SageMaker with minimal modification. The [SageMaker Python SDK](https://github.com/aws/sagemaker-python-sdk) handles transferring your script to a SageMaker training instance. On the training instance, SageMaker's native TensorFlow support sets up training-related environment variables and executes your training script. In this tutorial, we use the SageMaker Python SDK to launch a training job and deploy the trained model.

Script mode supports training with a Python script, a Python module, or a shell script. In this example, we use a Python script to train a classification model on the [MNIST dataset](http://yann.lecun.com/exdb/mnist/). In this example, we will show how easily you can train a SageMaker using TensorFlow 1.x and TensorFlow 2.0 scripts with SageMaker Python SDK. In addition, this notebook demonstrates how to perform real time inference with the [SageMaker TensorFlow Serving container](https://github.com/aws/sagemaker-tensorflow-serving-container). The TensorFlow Serving container is the default inference method for script mode. For full documentation on the TensorFlow Serving container, please visit [here](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/tensorflow/deploying_tensorflow_serving.rst).


## Set up the environment

Let's start by setting up the environment:

In [1]:
import os
import sagemaker
from sagemaker import get_execution_role

sagemaker_session = sagemaker.Session()

role = get_execution_role()
region = sagemaker_session.boto_session.region_name


ModuleNotFoundError: No module named 'sagemaker'

## Training Data

The MNIST dataset has been loaded to the public S3 buckets ``sagemaker-sample-data-<REGION>`` under the prefix ``tensorflow/mnist``. There are four ``.npy`` file under this prefix:
* ``train_data.npy``
* ``eval_data.npy``
* ``train_labels.npy``
* ``eval_labels.npy``

In [2]:
training_data_uri = "s3://sagemaker-sample-data-{}/tensorflow/mnist".format(region)


## Construct a script for distributed training

This tutorial's training script was adapted from an earlier version of TensorFlow's official [CNN MNIST example](https://github.com/tensorflow/tensorflow/blob/95e808ba44075dfe0b7db57bb49d2e64a1977a95/tensorflow/examples/tutorials/layers/cnn_mnist.py). An updated version is available at [Convolutional Neural Network (CNN)](https://github.com/tensorflow/docs/blob/master/site/en/tutorials/images/cnn.ipynb). We have modified the example to handle the ``model_dir`` parameter passed in by SageMaker. This is an S3 path which can be used for data sharing during distributed training and checkpointing and/or model persistence. We have also added an argument-parsing function to handle processing training-related variables.

At the end of the training job we have added a step to export the trained model to the path stored in the environment variable ``SM_MODEL_DIR``, which always points to ``/opt/ml/model``. This is critical because SageMaker uploads all the model artifacts in this folder to S3 at end of training.

Here is the entire script:

In [2]:
!pygmentize 'mnist.py'


# Copyright 2018-2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You
# may not use this file except in compliance with the License. A copy of
# the License is located at
#
#     http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
# ANY KIND, either express or implied. See the License for the specific
# language governing permissions and limitations under the License.
"""Convolutional Neural Network Estimator for MNIST, built with tf.layers."""

from __future__ import absolute_import, division, print_function

import argparse
import json
import logging as _logging
import os
import sys as _sys

import numpy as np
import tensorflow as tf
from tensorflow.python.platform import tf_logging


def cnn_model_fn(features, labels, mode):
    """Model function for CNN."""
    # Input Layer
    # Resha

## Create a training job using the `TensorFlow` estimator

The `sagemaker.tensorflow.TensorFlow` estimator handles locating the script mode container, uploading your script to a S3 location and creating a SageMaker training job. Let's call out a couple important parameters here:

* `py_version` is set to `'py3'` to indicate that we are using script mode since legacy mode supports only Python 2. Though Python 2 will be deprecated soon, you can use script mode with Python 2 by setting `py_version` to `'py2'` and `script_mode` to `True`.

* `distributions` is used to configure the distributed training setup. It's required only if you are doing distributed training either across a cluster of instances or across multiple GPUs. Here we are using parameter servers as the distributed training schema. SageMaker training jobs run on homogeneous clusters. To make parameter server more performant in the SageMaker setup, we run a parameter server on every instance in the cluster, so there is no need to specify the number of parameter servers to launch. Script mode also supports distributed training with [Horovod](https://github.com/horovod/horovod). You can find the full documentation on how to configure `distributions` [here](https://github.com/aws/sagemaker-python-sdk/tree/master/src/sagemaker/tensorflow#distributed-training). 



In [7]:
from sagemaker.tensorflow import TensorFlow

mnist_estimator = TensorFlow(
    entry_point="mnist.py",
    role=role,
    instance_count=1,
    instance_type="ml.p3.2xlarge",
    framework_version="1.15.2",
    py_version="py3",
    distribution={"parameter_server": {"enabled": True}},
)


## Calling ``fit``

To start a training job, we call `estimator.fit(training_data_uri)`.

An S3 location is used here as the input. `fit` creates a default channel named `'training'`, which points to this S3 location. In the training script we can then access the training data from the location stored in `SM_CHANNEL_TRAINING`. `fit` accepts a couple other types of input as well. See the API doc [here](https://sagemaker.readthedocs.io/en/stable/estimators.html#sagemaker.estimator.EstimatorBase.fit) for details.

When training starts, the TensorFlow container executes mnist.py, passing `hyperparameters` and `model_dir` from the estimator as script arguments. Because we didn't define either in this example, no hyperparameters are passed, and `model_dir` defaults to `s3://<DEFAULT_BUCKET>/<TRAINING_JOB_NAME>`, so the script execution is as follows:
```bash
python mnist.py --model_dir s3://<DEFAULT_BUCKET>/<TRAINING_JOB_NAME>
```
When training is complete, the training job will upload the saved model for TensorFlow serving.

In [9]:
mnist_estimator.fit(training_data_uri)

2022-08-08 18:43:20 Starting - Starting the training job...
2022-08-08 18:43:44 Starting - Preparing the instances for trainingProfilerReport-1659984199: InProgress
.........
2022-08-08 18:45:18 Downloading - Downloading input data
2022-08-08 18:45:18 Training - Downloading the training image...........WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/__init__.py:1473: The name tf.estimator.inputs is deprecated. Please use tf.compat.v1.estimator.inputs instead.
2022-08-08 18:47:01,013 sagemaker-containers INFO     Imported framework sagemaker_tensorflow_container.training
2022-08-08 18:47:01,758 sagemaker-containers INFO     Invoking user script
Training Env:
{
    "additional_framework_parameters": {
        "sagemaker_parameter_server_enabled": true
    },
    "channel_input_dirs": {
        "training": "/opt/ml/input/data/training"
    },
    "current_host": "algo-1",
    "framework_module": "sagemaker_tensorflow_container.training:main",
    "hosts": [



2022-08-08 18:47:04 Training - Training image download completed. Training in progress.INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into s3://sagemaker-us-east-2-485013493900/tensorflow-training-2022-08-08-18-43-19-456/model/model.ckpt.
INFO:tensorflow:Saving checkpoints for 0 into s3://sagemaker-us-east-2-485013493900/tensorflow-training-2022-08-08-18-43-19-456/model/model.ckpt.
INFO:tensorflow:loss = 2.2955675, step = 0
INFO:tensorflow:loss = 2.2955675, step = 0
INFO:tensorflow:global_step/sec: 284.872
INFO:tensorflow:global_step/sec: 284.872
INFO:tensorflow:loss = 2.312724, step = 100 (0.351 sec)
INFO:tensorflow:loss = 2.312724, step = 100 (0.351 sec)
INFO:ten

INFO:tensorflow:global_step/sec: 336.324
INFO:tensorflow:global_step/sec: 336.324
INFO:tensorflow:loss = 0.3661524, step = 5000 (0.297 sec)
INFO:tensorflow:loss = 0.3661524, step = 5000 (0.297 sec)
INFO:tensorflow:global_step/sec: 347.894
INFO:tensorflow:global_step/sec: 347.894
INFO:tensorflow:loss = 0.40155306, step = 5100 (0.287 sec)
INFO:tensorflow:loss = 0.40155306, step = 5100 (0.287 sec)
INFO:tensorflow:global_step/sec: 344.349
INFO:tensorflow:global_step/sec: 344.349
INFO:tensorflow:loss = 0.32213902, step = 5200 (0.290 sec)
INFO:tensorflow:loss = 0.32213902, step = 5200 (0.290 sec)
INFO:tensorflow:global_step/sec: 345.327
INFO:tensorflow:global_step/sec: 345.327
INFO:tensorflow:loss = 0.49204606, step = 5300 (0.289 sec)
INFO:tensorflow:loss = 0.49204606, step = 5300 (0.289 sec)
INFO:tensorflow:global_step/sec: 347.099
INFO:tensorflow:global_step/sec: 347.099
INFO:tensorflow:loss = 0.24868923, step = 5400 (0.288 sec)
INFO:tensorflow:loss = 0.24868923, step = 5400 (0.288 sec)
IN

INFO:tensorflow:global_step/sec: 346.59
INFO:tensorflow:global_step/sec: 346.59
INFO:tensorflow:loss = 0.15500346, step = 11900 (0.289 sec)
INFO:tensorflow:loss = 0.15500346, step = 11900 (0.289 sec)
INFO:tensorflow:global_step/sec: 344.19
INFO:tensorflow:global_step/sec: 344.19
INFO:tensorflow:loss = 0.17841873, step = 12000 (0.290 sec)
INFO:tensorflow:loss = 0.17841873, step = 12000 (0.290 sec)
INFO:tensorflow:global_step/sec: 345.132
INFO:tensorflow:global_step/sec: 345.132
INFO:tensorflow:loss = 0.27887893, step = 12100 (0.290 sec)
INFO:tensorflow:loss = 0.27887893, step = 12100 (0.290 sec)
INFO:tensorflow:global_step/sec: 343.461
INFO:tensorflow:global_step/sec: 343.461
INFO:tensorflow:loss = 0.24708235, step = 12200 (0.291 sec)
INFO:tensorflow:loss = 0.24708235, step = 12200 (0.291 sec)
INFO:tensorflow:global_step/sec: 344.04
INFO:tensorflow:global_step/sec: 344.04
INFO:tensorflow:loss = 0.2068808, step = 12300 (0.291 sec)
INFO:tensorflow:loss = 0.2068808, step = 12300 (0.291 sec

INFO:tensorflow:global_step/sec: 342.664
INFO:tensorflow:global_step/sec: 342.664
INFO:tensorflow:loss = 0.15383583, step = 18700 (0.292 sec)
INFO:tensorflow:loss = 0.15383583, step = 18700 (0.292 sec)
INFO:tensorflow:global_step/sec: 348.772
INFO:tensorflow:global_step/sec: 348.772
INFO:tensorflow:loss = 0.1366972, step = 18800 (0.287 sec)
INFO:tensorflow:loss = 0.1366972, step = 18800 (0.287 sec)
INFO:tensorflow:global_step/sec: 341.006
INFO:tensorflow:global_step/sec: 341.006
INFO:tensorflow:loss = 0.14849713, step = 18900 (0.293 sec)
INFO:tensorflow:loss = 0.14849713, step = 18900 (0.293 sec)
INFO:tensorflow:global_step/sec: 342.615
INFO:tensorflow:global_step/sec: 342.615
INFO:tensorflow:loss = 0.10344326, step = 19000 (0.292 sec)
INFO:tensorflow:loss = 0.10344326, step = 19000 (0.292 sec)
INFO:tensorflow:global_step/sec: 343.365
INFO:tensorflow:global_step/sec: 343.365
INFO:tensorflow:loss = 0.06524114, step = 19100 (0.291 sec)
INFO:tensorflow:loss = 0.06524114, step = 19100 (0.2


2022-08-08 18:48:44 Uploading - Uploading generated training model
2022-08-08 18:48:44 Completed - Training job completed
ProfilerReport-1659984199: NoIssuesFound
Training seconds: 212
Billable seconds: 212


## Deploy the trained model to an endpoint

The `deploy()` method creates a SageMaker model, which is then deployed to an endpoint to serve prediction requests in real time. We will use the TensorFlow Serving container for the endpoint, because we trained with script mode. This serving container runs an implementation of a web server that is compatible with SageMaker hosting protocol. The [Using your own inference code]() document explains how SageMaker runs inference containers.

In [10]:
predictor = mnist_estimator.deploy(initial_instance_count=1, instance_type="ml.p2.xlarge")


update_endpoint is a no-op in sagemaker>=2.
See: https://sagemaker.readthedocs.io/en/stable/v2.html for details.


-------!

## Invoke the endpoint

Let's download the training data and use that as input for inference.

In [11]:
!aws --region {region} s3 cp s3://sagemaker-sample-data-{region}/tensorflow/mnist/train_data.npy train_data.npy
!aws --region {region} s3 cp s3://sagemaker-sample-data-{region}/tensorflow/mnist/train_labels.npy train_labels.npy


download: s3://sagemaker-sample-data-us-east-2/tensorflow/mnist/train_data.npy to ./train_data.npy
download: s3://sagemaker-sample-data-us-east-2/tensorflow/mnist/train_labels.npy to ./train_labels.npy


In [2]:
import numpy as np

train_data = np.load("train_data.npy")
train_labels = np.load("train_labels.npy")


In [3]:
print(train_labels.shape)
print("train_labels[%i]:" % len(train_labels), train_labels)


(55000,)
train_labels[55000]: [7 3 4 ... 5 6 8]


In [4]:
print(train_data.shape)
print("train_data[%i]:" % len(train_data), train_data)


(55000, 784)
train_data[55000]: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


The formats of the input and the output data correspond directly to the request and response formats of the `Predict` method in the [TensorFlow Serving REST API](https://www.tensorflow.org/serving/api_rest). SageMaker's TensforFlow Serving endpoints can also accept additional input formats that are not part of the TensorFlow REST API, including the simplified JSON format, line-delimited JSON objects ("jsons" or "jsonlines"), and CSV data.

In this example we are using a `numpy` array as input, which will be serialized into the simplified JSON format. In addtion, TensorFlow serving can also process multiple items at once as you can see in the following code. You can find the complete documentation on how to make predictions against a TensorFlow serving SageMaker endpoint [here](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/tensorflow/deploying_tensorflow_serving.rst#making-predictions-against-a-sagemaker-endpoint).

In [12]:
predictions = predictor.predict(train_data[:50])
for i in range(0, 50):
    prediction = predictions["predictions"][i]["classes"]
    label = train_labels[i]
    print(
        "prediction is {}, label is {}, matched: {}".format(prediction, label, prediction == label)
    )
    

prediction is 7, label is 7, matched: True
prediction is 3, label is 3, matched: True
prediction is 4, label is 4, matched: True
prediction is 6, label is 6, matched: True
prediction is 1, label is 1, matched: True
prediction is 8, label is 8, matched: True
prediction is 1, label is 1, matched: True
prediction is 0, label is 0, matched: True
prediction is 9, label is 9, matched: True
prediction is 8, label is 8, matched: True
prediction is 0, label is 0, matched: True
prediction is 3, label is 3, matched: True
prediction is 1, label is 1, matched: True
prediction is 3, label is 2, matched: False
prediction is 7, label is 7, matched: True
prediction is 0, label is 0, matched: True
prediction is 2, label is 2, matched: True
prediction is 9, label is 9, matched: True
prediction is 6, label is 6, matched: True
prediction is 0, label is 0, matched: True
prediction is 1, label is 1, matched: True
prediction is 6, label is 6, matched: True
prediction is 7, label is 7, matched: True
prediction

## Delete the endpoint

Let's delete the endpoint we just created to prevent incurring any extra costs.

In [14]:
predictor.delete_endpoint()
